version: "3.9"

networks:
  dev-network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - dev-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - dev-network
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dev-network
    depends_on:
      - backend

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    networks:
      - dev-network
    depends_on:
      - frontend
