###
# @name Get xps
GET http://localhost:8080/api/v1/xp

###
# @name Add xp
POST http://localhost:8080/api/v1/xp
Content-Type: application/json

{
  "check_id": 2,
  "xp_amount": 770
}

###
# @name Update xp
PATCH http://localhost:8080/api/v1/xp
Content-Type: application/json

{
  "id": 1,
  "check_id": 1,
  "xp_amount": 300
}

###
# @name Delete xps
DELETE http://localhost:8080/api/v1/xp/1